version: "2"
services:
  node:
    image: "node:6"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./::/home/node/app
    expose:
      - "80"
    command: "npm start"
